# Predict the price of Bangalore Houses

# Linear Regression Algorithm - Day 1 

In [1]:
# Importing Libraries
import pandas as pd
import matplotlib as plt
import numpy as np
import seaborn as sns
from sklearn.linear_model import LinearRegression

Load DataSet

In [2]:
train = pd.read_csv(r"D:\Coding\GitHub\Machine Learning\Machine Learning Practice\Machine Learning Data\train.csv")

In [3]:
test = pd.read_csv(r"D:\Coding\GitHub\Machine Learning\Machine Learning Practice\Machine Learning Data\test.csv")

In [4]:
train.head()

x          y
0  24.0  21.549452
1  50.0  47.464463
2  15.0  17.218656
3  38.0  36.586398
4  87.0  87.288984

In [5]:
test.head()

x          y
0  77  79.775152
1  21  23.177279
2  22  25.609262
3  20  17.857388
4  36  41.849864

In [21]:
train.shape
print(train.isnull().sum())
type(train)

x    0
y    0
dtype: int64


AttributeError: 'DataFrame' object has no attribute 'type'

In [22]:
test.shape
print(test.isnull().sum())
type(test)

x    0
y    0
dtype: int64


pandas.core.frame.DataFrame

In [8]:
x_train = train['x']
y_train = train['y']
print(x_train)
print(y_train)

0      24.0
1      50.0
2      15.0
3      38.0
4      87.0
       ... 
695    58.0
696    93.0
697    82.0
698    66.0
699    97.0
Name: x, Length: 700, dtype: float64
0      21.549452
1      47.464463
2      17.218656
3      36.586398
4      87.288984
         ...    
695    58.595006
696    94.625094
697    88.603770
698    63.648685
699    94.975266
Name: y, Length: 700, dtype: float64


In [9]:
x_test = test['x']
y_test = test['y']
print(x_test)
print(y_test)

0      77
1      21
2      22
3      20
4      36
       ..
295    71
296    46
297    55
298    62
299    47
Name: x, Length: 300, dtype: int64
0      79.775152
1      23.177279
2      25.609262
3      17.857388
4      41.849864
         ...    
295    68.545888
296    47.334876
297    54.090637
298    63.297171
299    52.459467
Name: y, Length: 300, dtype: float64


In [10]:
y_train.fillna(value=y_train.mean(), inplace=True)
print(y_train.mean())
y_train.isnull().sum()

49.939869170457804


0

In [11]:
lr = LinearRegression()
# Reshaping Array
x = x_train.to_numpy()
lr.fit(x.reshape(-1, 1), y_train)

LinearRegression()

In [12]:
#  Intercept values
lr.intercept_

47.400466270549664

In [13]:
lr.coef_

array([0.04618277])

In [20]:
lr.predict(x_test[0].reshape(-1, 1))

array([50.95653945])

In [24]:

lr.predict(x_test.to_numpy().reshape(-1, 1))

array([50.95653945, 48.37030441, 48.41648718, 48.32412164, 49.06304594,
       48.0932078 , 50.26379792, 51.78782928, 48.32412164, 47.63138011,
       47.58519734, 48.27793887, 51.83401205, 50.26379792, 49.06304594,
       48.0932078 , 50.40234623, 48.04702503, 51.41836714, 50.5870773 ,
       51.51073267, 49.75578747, 51.51073267, 48.64740102, 51.88019482,
       50.07906685, 51.04890499, 48.37030441, 51.69546375, 48.64740102,
       51.97256036, 48.8321321 , 48.92449763, 51.09508776, 48.69358379,
       49.57105639, 49.848153  , 50.5870773 , 48.69358379, 48.92449763,
       51.60309821, 50.67944284, 49.7096047 , 50.91035668, 47.58519734,
       49.10922871, 50.63326007, 50.54089453, 49.24777701, 49.01686317,
       51.74164652, 51.4645499 , 49.80197024, 48.8321321 , 50.12524962,
       47.40046627, 49.20159424, 50.35616346, 50.5870773 , 50.03288408,
       48.00084226, 50.72562561, 50.91035668, 50.21761515, 51.18745329,
       48.2317561 , 49.29395978, 49.7096047 , 49.94051854, 48.00

In [27]:
lr.score(y_test.to_numpy().reshape(-1, 1), x_test.to_numpy().reshape(-1, 1))

0.08977653425803056